In [231]:
import pandas as pd
import numpy as np
import math
import cvxopt

In [288]:
X = pd.read_fwf('Data/logistic_x.txt', header=None)
y = pd.read_fwf('Data/logistic_y.txt', header=None)

X[2] = 1
X = np.array(X)
y = np.array(y)

thetas = np.zeros(X.shape[1]).reshape((3,1))
thetas


array([[0.],
       [0.],
       [0.]])

Batch Gradient Descent

In [222]:
thetas = np.zeros(X.shape[1]).reshape((3,1))
thetas

def cost_function(X, y, beta):
    """
    cost_function(X, y, beta) computes the cost of using beta as the
    parameter for linear regression to fit the data points in X and y
    """
    ## number of training examples
    m = len(y)
    loss = 0
    ## Calculate the cost with the given parameters
    hypothesis = X.dot(beta)
    for i in range(X.shape[0]):
        loss += (hypothesis[i]-y[i])**2
        J = 1 / 2 * loss

    return J

cost_function(X, y, thetas)

def gradient_descent(X, y, beta, alpha, iterations):
    """
    gradient_descent() performs gradient descent to learn beta by
    taking num_iters gradient steps with learning rate alpha
    """
    cost_history = [0] * iterations

    for iteration in range(iterations):
        hypothesis = X.dot(beta)
        for j in range(X.shape[1]):
            gradient = 0
            for i in range(X.shape[0]):
                gradient += (hypothesis[i]-y[i])*X[i,j]
            beta[j] = beta[j] - alpha*gradient
        cost = cost_function(X, y, beta)
        cost_history[iteration] = cost

        ## If you really want to merge everything in one line:
        # beta = beta - alpha * (X.T.dot(X.dot(beta)-y)/m)
        # cost = cost_function(X, y, beta)
        # cost_history[iteration] = cost

    return beta, cost_history

alpha = 0.0005
(b, c) = gradient_descent(X, y, thetas, alpha, 100)
c

[array([41.35229232]),
 array([36.94667679]),
 array([33.80560234]),
 array([31.55975723]),
 array([29.9479718]),
 array([28.78537391]),
 array([27.94109771]),
 array([27.32250518]),
 array([26.86401745]),
 array([26.51920925]),
 array([26.25521307]),
 array([26.04875814]),
 array([25.88336678]),
 array([25.74736977]),
 array([25.63250163]),
 array([25.53290624]),
 array([25.44443301]),
 array([25.36413871]),
 array([25.28993478]),
 array([25.22033773]),
 array([25.15429245]),
 array([25.09104716]),
 array([25.03006482]),
 array([24.97096052]),
 array([24.9134571]),
 array([24.85735376]),
 array([24.8025038]),
 array([24.74879892]),
 array([24.69615807]),
 array([24.64451955]),
 array([24.59383546]),
 array([24.54406771]),
 array([24.49518523]),
 array([24.44716202]),
 array([24.39997569]),
 array([24.3536065]),
 array([24.30803665]),
 array([24.26324979]),
 array([24.21923062]),
 array([24.1759647]),
 array([24.13343822]),
 array([24.09163789]),
 array([24.05055086]),
 array([24.01016

Stochastic Gradient Descent


In [289]:
X.dot(thetas)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

In [219]:
thetas = np.zeros(X.shape[1]).reshape((3,1))
thetas

def cost_function(X, y, beta):
    """
    cost_function(X, y, beta) computes the cost of using beta as the
    parameter for linear regression to fit the data points in X and y
    """
    ## number of training examples
    m = len(y)

    ## Calculate the cost with the given parameters
    J = 1/2*(X.dot(beta)-y).T.dot((X.dot(beta)-y))

    return J

cost_function(X, y, thetas)

def gradient_descent(X, y, beta, alpha, iterations):
    """
    gradient_descent() performs gradient descent to learn beta by
    taking num_iters gradient steps with learning rate alpha
    """
    cost_history = [0] * iterations

    for iteration in range(iterations):
        hypothesis = X.dot(beta)
        loss = hypothesis-y
        gradient = X.T.dot(loss)
        beta = beta - alpha*gradient
        cost = cost_function(X, y, beta)
        cost_history[iteration] = cost

        ## If you really want to merge everything in one line:
        # beta = beta - alpha * (X.T.dot(X.dot(beta)-y)/m)
        # cost = cost_function(X, y, beta)
        # cost_history[iteration] = cost

    return beta, cost_history

alpha = 0.0005
(b, c) = gradient_descent(X, y, thetas, alpha, 100)
c

[array([[41.35229232]]),
 array([[36.94667679]]),
 array([[33.80560234]]),
 array([[31.55975723]]),
 array([[29.9479718]]),
 array([[28.78537391]]),
 array([[27.94109771]]),
 array([[27.32250518]]),
 array([[26.86401745]]),
 array([[26.51920925]]),
 array([[26.25521307]]),
 array([[26.04875814]]),
 array([[25.88336678]]),
 array([[25.74736977]]),
 array([[25.63250163]]),
 array([[25.53290624]]),
 array([[25.44443301]]),
 array([[25.36413871]]),
 array([[25.28993478]]),
 array([[25.22033773]]),
 array([[25.15429245]]),
 array([[25.09104716]]),
 array([[25.03006482]]),
 array([[24.97096052]]),
 array([[24.9134571]]),
 array([[24.85735376]]),
 array([[24.8025038]]),
 array([[24.74879892]]),
 array([[24.69615807]]),
 array([[24.64451955]]),
 array([[24.59383546]]),
 array([[24.54406771]]),
 array([[24.49518523]]),
 array([[24.44716202]]),
 array([[24.39997569]]),
 array([[24.3536065]]),
 array([[24.30803665]]),
 array([[24.26324979]]),
 array([[24.21923062]]),
 array([[24.1759647]]),
 arra

Logistic Regression Gradient Descent

In [246]:
thetas = np.zeros(X.shape[1]).reshape((3,1))
thetas

def cost_function(X, y, beta):
    """
    cost_function(X, y, beta) computes the cost of using beta as the
    parameter for linear regression to fit the data points in X and y
    """
    ## number of training examples
    m = len(y)
    hypothesis = 1/(1+math.e**(-(X.dot(beta))))
    ## Calculate the cost with the given parameters
    J = 1/2*(hypothesis-y).T.dot((hypothesis-y))

    return J


def gradient_descent(X, y, beta, alpha, iterations):
    """
    gradient_descent() performs gradient descent to learn beta by
    taking num_iters gradient steps with learning rate alpha
    """
    cost_history = [0] * iterations
    hypothesis = 1/(1+math.e**(-(X.dot(beta))))
    for iteration in range(iterations):
        loss = hypothesis-y
        gradient = X.T.dot(loss)
        beta = beta - alpha*gradient
        cost = cost_function(X, y, beta)
        cost_history[iteration] = cost

        ## If you really want to merge everything in one line:
        # beta = beta - alpha * (X.T.dot(X.dot(beta)-y)/m)
        # cost = cost_function(X, y, beta)
        # cost_history[iteration] = cost

    return beta, cost_history

alpha = 0.0005
(b, c) = gradient_descent(X, y, thetas, alpha, 100)
b

array([[-4.94325123],
       [ 6.35832332],
       [-2.525     ]])

In [269]:
import sympy
thetas = np.zeros(X.shape[1]).reshape((3,1))
thetas

def sigmoid(x, theta):
    return 1/(1-math.e**(-theta.T.dot(x)))
def hessian(x):
    """
    Calculate the hessian matrix with finite differences
    Parameters:
       - x : ndarray
    Returns:
       an array of shape (x.dim, x.ndim) + x.shape
       where the array[i, j, ...] corresponds to the second derivative x_ij
    """
    diag = np.empty(x.shape[0])
    hessian = np.empty([x.shape[0], x.shape[0]])
    for i in range(x.shape[0]):
        diag[i] = sigmoid(x[i,:], thetas).dot(sigmoid(-x[i,:], thetas))
        hessian[i,i] = (x[i,:].dot(x[i,:].T))*(diag[i])


    return hessian

hessian(X)

/var/folders/4t/jqgtn_7128l6cw1_29rck3t40000gn/T/ipykernel_40346/3680592327.py:6: RuntimeWarning: divide by zero encountered in true_divide
  return 1/(1-math.e**(-theta.T.dot(x)))


array([[             inf,  2.02369289e-320,  2.24336921e-314, ...,
         9.42795298e-264,  2.40307842e-306,  8.06648694e-308],
       [             nan,              inf,              nan, ...,
                     nan,              nan,  1.79186525e-298],
       [             nan,              nan,              inf, ...,
                     nan,  2.16517159e-299,  1.23983118e-302],
       ...,
       [ 6.44533354e-311,  1.59761465e-279,  1.53726994e-311, ...,
                     inf,  3.99546069e+252,  7.34295013e+223],
       [ 2.42368889e+188,  6.93890661e+218,  1.33360360e+241, ...,
         2.76217432e+257,              inf,  2.10992986e-312],
       [ 0.00000000e+000,  4.88907831e-311,  8.80117766e-282, ...,
        -8.25259115e+252,  7.84019370e-061,              inf]])

In [350]:
thetas = np.zeros(X.shape[1]).reshape((3,1))
thetas
def sigmoid(func):
    return 1/(1+np.exp(-func))

def grad(x, y, beta):
    z = y*x.dot(beta)
    return np.array((1-sigmoid(z))*-y*x)

def hessian(x, y, beta):

    hessian = np.zeros([X.shape[1], X.shape[1]])
    z = y*x.dot(beta)

    for j in range(X.shape[1]):
        for i in range(X.shape[1]):
            hessian[i,j] = np.mean(sigmoid(z)*(1-sigmoid(z))*x[:,i]*x[:,j])
    return hessian

def hess_l(theta, x, y):
    hess = np.zeros((x.shape[1], x.shape[1]))
    z = y*x.dot(theta)
    for i in range(hess.shape[0]):
        for j in range(hess.shape[0]):
            if i <= j:
                hess[i][j] = np.mean(sigmoid(z)*(1-sigmoid(z))*x[:,i]*x[:,j])
                if i != j:
                    hess[j][i] = hess[i][j]
    return hess


# hess_l(thetas, X, y)
grad(X, y, thetas)

array([[ 0.6716252 , -0.66557395,  0.5       ],
       [ 0.91027645, -0.31733405,  0.5       ],
       [ 0.49316034, -0.9442881 ,  0.5       ],
       [ 0.9721867 , -0.817726  ,  0.5       ],
       [ 0.48836676, -0.67665755,  0.5       ],
       [ 0.9729292 , -1.0221639 ,  0.5       ],
       [ 1.05375765, -1.0628342 ,  0.5       ],
       [ 1.0351865 , -1.23170505,  0.5       ],
       [ 0.43432482, -1.2059674 ,  0.5       ],
       [ 0.9003297 , -1.38698445,  0.5       ],
       [ 1.56418935, -1.7226216 ,  0.5       ],
       [ 1.54737145, -1.82230725,  0.5       ],
       [ 1.4543326 , -2.00325185,  0.5       ],
       [ 1.3385169 , -1.5099296 ,  0.5       ],
       [ 1.37293355, -1.35502805,  0.5       ],
       [ 2.08573235, -1.7311241 ,  0.5       ],
       [ 1.965661  , -1.0549522 ,  0.5       ],
       [ 2.1893435 , -1.19023715,  0.5       ],
       [ 2.40082825, -1.6901672 ,  0.5       ],
       [ 2.0830525 , -1.4069422 ,  0.5       ],
       [ 1.23350705, -0.8054222 ,  0.5  

Newton's Method

In [353]:
thetas = np.zeros(X.shape[1]).reshape((3,1))
thetas

def cost_function(x, y, beta):
    """
    cost_function(X, y, beta) computes the cost of using beta as the
    parameter for linear regression to fit the data points in X and y
    """
    ## number of training examples
    m = len(y)
    hypothesis = y*x.dot(beta)
    ## Calculate the cost with the given parameters
    J = np.log(1 + np.exp(-hypothesis))

    return J


def newtons_method(x, y, beta, iterations):
    """
    gradient_descent() performs gradient descent to learn beta by
    taking num_iters gradient steps with learning rate alpha
    """
    cost_history = [0] * iterations
    hypothesis = y*x.dot(beta)
    for iteration in range(iterations):
        gradient = grad(x, y, beta)
        inv_hessian = np.linalg.inv(hessian(x, y, beta))
        beta = beta - inv_hessian.dot(gradient.T)
        cost = cost_function(X, y, beta)
        cost_history[iteration] = cost

        ## If you really want to merge everything in one line:
        # beta = beta - alpha * (X.T.dot(X.dot(beta)-y)/m)
        # cost = cost_function(X, y, beta)
        # cost_history[iteration] = cost

    return beta, cost_history

(b, c) = newtons_method(X, y, thetas, 100)
b

ValueError: operands could not be broadcast together with shapes (99,99) (99,3) 